### ISSUE TITLE
Sensor update time

### ISSUE THREAD

**Issue by swissmaster1** [dynasticorpheus/gigasetelements-ha#15]
How often will the sensor status being updated from the cloud? I tested a sensor on a door with that integration to give me a notification as soon as a door is opened. Most of the time when I open the door fast and close it again I didnt get a notification. But when the door stays open for some time it worked. In the Gigaset Elements protocol I can see that every opening was recognized correctly. 
What I like to do is to trigger some kind of action as soon as the door will be opened. But this is not possible when some door openings stays undetected.

**Comment by dynasticorpheus** [comment]
@swissmaster1 I will improve the code as to not miss events happening (open and close) between consecutive API calls. A small delay will always be there as events are pulled and not pushed.

**Comment by swissmaster1** [comment]
How long can the delay be max. under normal circumstances?

**Comment by dynasticorpheus** [comment]
@swissmaster1 Can you please test version 0.3.0b0 which should capture all (binary) events even if they occur within the 10 second update time frame. You can enable beta releases by choosing reinstall option in hacs.

**Comment by swissmaster1** [comment]
Installed and shortly tested. Out of 10 tries it recognized now 10 openings. Will test it the next few day a little bit more but I think its good like this. How is the 10 second update time defined? Can this time being shortened to get faster recognition?

**Comment by dynasticorpheus** [comment]
Fixed ec27a09
