### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by maltejarr** [dynasticorpheus/gigasetelements-ha#17]
First of all, good job!

When using the integration and not having any base station, HA throws an Index Error in custom_components/gigasetelements/__init__.py:121.

I am using Gigaset Elements only for the Go telephone notification for nothing else.
I would be very happy to see an update of the integration to include the phones too. My personal interest is getting the caller id displayed in HA.

**Comment by dynasticorpheus** [comment]
@maltejarr  Would you be able to to run below python script with username/password and share the output so I can see how phone related events look? Please mask any private information but ensure the length and type remain the same.

`python3 script.py test@me.com topsecret`

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

_AUTHOR_ = "dynasticorpheus@gmail.com"
_VERSION_ = "2021.5.0"

import sys
import requests

post_header = {"user-agent": "Mozilla/5.0"}
get_header = {"content-type": "application/json; charset=UTF-8"}

s = requests.Session()

r = s.post(
    "https://im.gigaset-elements.de/identity/api/v1/user/login",
    data={"password": sys.argv[2], "email": sys.argv[1]},
    allow_redirects=True,
    headers=post_header)

r = s.get(
    "https://api.gigaset-elements.de/api/v1/auth/openid/begin?op=gigaset",
    headers=get_header,
    allow_redirects=True)

r = s.get(
    "https://api.gigaset-elements.de/api/v2/me/events?limit=10&group=phone",
    headers=get_header,
    allow_redirects=True)

print(r.text)
```

This script could already be useful in combination with a command line sensor as per https://www.home-assistant.io/integrations/sensor.command_line.

**Comment by maltejarr** [comment]
@dynoasticorpheus Thanks a lot for the quick reaction on this feature
request.
I got an IT background, nevertheless I have not understood completly HA and
its mechanics.
What I have tried without any luck is running the two scrips (the shell
script and the python script) from the terminal of HA. Since python3 is an
unknow command on the terminal I have tried to call it as a service from
the developer tools of HA.

Can you please give me a hint, what I am doing wrong? I know the error sits
in front of the monitor...

For the shell script I receive a reddir error.
For the python script as a service call I receive the following error:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:132
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:04:27 (2 occurrences)
Last logged: 11:13:54

[547347144032] Error handling message: Service python_script.connect_script
"mail" "password" does not match format <domain>.<name> for dictionary
value @ data['sequence'][0]['service']. Got 'python_script.connect_script
"mail" "password"'

Sadly python is not a programming language I am used to. And to be honest I
am not into programming anymore.

Am Sa., 15. Mai 2021 um 12:04 Uhr schrieb dynasticorpheus <
***@***.***>:

**Comment by maltejarr** [comment]
@dynasticorpheus Ok, I got the python script working on my windows pc. I
assume the output of the python and the shell script should be the same, so
I drop the shell script. Please find the output below. I have replace the
most private data by XXX.
Please feel free to contact me again for more data, if needed. I really
appreciate your work and support!

{"events":[{"id":"e269021905224d61c7004a307d6f13e5244c157d","state":"ok","ts":"1621176324163","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"accepted","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"80f20bb04aaea704d0359a346f66116914e17d99","state":"ok","ts":"1621176230223","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"outgoing","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"1b0a1d8cd116bfb34dcfc4f0732ad516f097bf2a","state":"ok","ts":"1621160121990","type":"gp.am_icm","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.am_icm","line_index":1,"clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"},"am_index":1},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"879ddb7fc915b97df975dc1b06197781ad6d5900","state":"ok","ts":"1620982118840","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"outgoing","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"677bcaa5d892af03dd36c99841bbfe9b618fa9b8","state":"ok","ts":"1620752522200","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"accepted","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"fb05cd47e24c17420528fb4f120cc85aeacd1e84","state":"ok","ts":"1620752466304","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"outgoing","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"9467d53d846284d8ae87e5ff421310b8d1b1a987","state":"ok","ts":"1620750391380","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"outgoing","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"6134b5dc4f65321592a97dec4c17be926441a6ef","state":"ok","ts":"1620730212330","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"outgoing","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"},{"id":"471b60986341412b88f319fd2e2ebff4fd06cad8","state":"ok","ts":"1620728013271","type":"gp.call","o":{"frontendTags":{"room":{"roomName":"Diele"}},"friendly_name":"Gigaset
Telefon","dialable":true,"line_type":"voip","line_name":"XXX","type":"gp02.call","line_index":1,"call_type":"missed","clip_type":"number","clip":"XXX","room":{"id":379406,"friendlyName":"Diele"}},"source_id":"7C2F80A9FDB6","source_type":"gp02","state_pre":"ok"}],"home_state":"ok"}

line_name: friendly name for the phone line in the phone base station,
replaced by XXX
clip: phone number which has been called or which has called, replaced by
XXX, i.e. "00491231234567"

Am Mo., 17. Mai 2021 um 11:20 Uhr schrieb Malte Jarr ***@***.***>:

**Comment by dynasticorpheus** [comment]
For now I won't be able to work on this kind of setup hence closing.
