### ISSUE TITLE
i see not all of my Gigaset produkts

### ISSUE THREAD

**Issue by Sir-Udo** [dynasticorpheus/gigasetelements-ha#27]
Hello,

I have a problem, I have 8 Thermostat 3 climate and 4 water sensors.
This all at 3 homebases from Gigaset.
All are connected to one Gigaset account.
In the Gigaset app, all is ok.
In Home assistant I saw only one base and with the HASC version 2023 one climate or I use the version 2022 than I see one base and one thermostat. 
Can you help me?

**Comment by dynasticorpheus** [comment]
Currently there is no support for multi home base  hence it will pick one.

**Comment by Sir-Udo** [comment]
ok, thank you for youre answer.
but it shows not all of the sensors from the one base he find. 
with the version 2022 he find one thermostat at this base, from 3 thermostats.
with the version 2023 he find one climate from this base. 
if i can help to make its works, please tell me.
thx Udo

**Comment by dynasticorpheus** [comment]
I added the option to force base ID to be used in [develop](https://github.com/dynasticorpheus/gigasetelements-ha/tree/develop) version. Perhaps you can install and set additional option in **configuration.yaml** so hopefully you can at least control one base/sensor combo without issues?

`mac: F52A76D4CDC1B660A0E0D17EGD3275B6`

If you can install cli and provide the generated file of below command as attachment. This should contain all base ID's where you need to pick the one linked to **bs01** and add to config but also give me an idea how a multi home setup looks from API response point of view. My guess you would also have a bs02 and bs03 entry.

`gigasetelements-cli --username email@domain.com --password secret --elements output.json`

  https://github.com/dynasticorpheus/gigasetelements-cli

disclaimer: I have only one base so difficult to test properly.

**Comment by Sir-Udo** [comment]
Hi, i try to install the cli version, but:
<Integration dynasticorpheus/gigasetelements-cli> Repository structure for 2023.4.0 is not compliant
what do i wrong?

**Comment by dynasticorpheus** [comment]
The cli is a separate program not linked to HA at all. Running below command should be fine:

`pip install gigasetelements-cli`

or

`pip3 install gigasetelements-cli`

**Comment by Sir-Udo** [comment]
i'm sorry, i try it in the terminal, and is not work? 
sorry, i use HA since 3 month, 
bash: pip (or3) command not found both with 3 or without the same
if its help, i install HA at Hyper-V on Windows Server 2019

**Comment by Sir-Udo** [comment]
hi again, now i have test it, but...
<img width="847" alt="image" src="https://github.com/dynasticorpheus/gigasetelements-ha/assets/143514625/d8784a25-4754-42d3-a892-aa49858bc5ae">

and it is no file generated

**Comment by dynasticorpheus** [comment]
I have linked a second base to my setup to see if I can make it work in a multi base setup but this will take some time as it works quite differently than expected and needs a lot of changes in the code.

**Comment by Sir-Udo** [comment]
Thank you 4 youre help.
if I can do something, tell me, i try to do my best. 
python and co is new 4 me, but i learn fast:-)

**Comment by dynasticorpheus** [comment]
> hi again, now i have test it, but... <img alt="image" width="847" src="https://user-images.githubusercontent.com/143514625/280060059-d8784a25-4754-42d3-a892-aa49858bc5ae.png">
> 
> and it is no file generated

I think you are missing some requirements run below command using pip or pip3

`pip install configargparse>=0.12.0 future>=0.15.2 requests>=2.9.1 colorama>=0.3.7 python-crontab>=2.0.1 pushbullet.py>=0.10.0 unidecode>=0.4.19 daemonize>=2.4.6
`

Also wondering if you are using multiple base in one house or are they setup as separate houses?

**Comment by Sir-Udo** [comment]
Hi, 
sorry looks the same,..
<img width="851" alt="image" src="https://github.com/dynasticorpheus/gigasetelements-ha/assets/143514625/b5b330bb-a2ee-43b3-a018-a4bc36ec2588">
Why more? 
ouer house is old and have very thig wals, one is to bad to have a stabil connection.
the otherone is at my mother in law's house. she is around 80jears old and have no smartphone.

**Comment by dynasticorpheus** [comment]
Ok so just to be clear, you have two houses (systems) setup in the app? E.g. you switch system in the app in case you want to see info from your mother in law, correct?

Let's try a different approach to get the info:

1. Log in below site using **chrome** browser
2. Right-click anywhere on the page and select **inspect**
3. Select **network** tab
4. Add **api** to filter box
5. Select **elements** in **name** column
6. Select **response** tab 
7. Copy/paste all text and and **randomize** private info but keeping structure / length / format the same 
8. **Share** to dynasticorpheus via personal message on [community](https://community.home-assistant.io/t/gigaset-elements/222444)

[https://app.gigaset-elements.com](https://app.gigaset-elements.com/)

**Comment by Sir-Udo** [comment]
Hi, i'm sorry, i dont find something to pm you? 
i'm to stupid :-)

in the app, i have all in one house. the other usedcase with both houses are not ok for me.

a other queastion:
from all the elements??
![image](https://github.com/dynasticorpheus/gigasetelements-ha/assets/143514625/b77e6d69-e40b-42e7-b1f7-49a37c07a6aa)

here are two excample
![image](https://github.com/dynasticorpheus/gigasetelements-ha/assets/143514625/106eb3d6-588c-41de-8091-9828552eab32)
![image](https://github.com/dynasticorpheus/gigasetelements-ha/assets/143514625/b4bf6df2-5b21-4de3-be06-9a8a232e308b)

every elements objekt are 
![image](https://github.com/dynasticorpheus/gigasetelements-ha/assets/143514625/4238b5f0-1d70-4df4-9a1b-7c6271799b8e)

like this long

**Comment by dynasticorpheus** [comment]
I only need exported file of one of the elements api calls. Sign up at home assistant community using your github account credentials at below url. From there you can PM me, github doesn't have PM functionality hence this route.

https://community.home-assistant.io/

**Comment by Sir-Udo** [comment]
I'm sorry but I don't find it. 
Please send me a PM, sorry, 
Sir-Udo
Sir Udo

**Comment by dynasticorpheus** [comment]
@Sir-Udo  Will take some time to complete but I have started working on multi-base support.

**Comment by Sir-Udo** [comment]
Hi and many thanx, if i can help please tell me.

**Comment by dynasticorpheus** [comment]
End of service March 29th hence closing this issue :(

**Comment by Sir-Udo** [comment]
thx 4 all, all the work,..... ;-(
