### ISSUE TITLE
feature request: privacy settings

### ISSUE THREAD

**Issue by SilleDE** [dynasticorpheus/gigasetelements-ha#28]
Hi dynasticorpheus,

with gigasetelements-cli there is the option of switching privacy settings:

gigasetelements-cli -c gigasetelements-cli.conf -y on -j
gigasetelements-cli -c gigasetelements-cli.conf -y off -j

I would also like this option for gigasetelements-ha. It would be nice if you could implement this.

Sille

**Comment by dynasticorpheus** [comment]
@SilleDE  I am currently testing this functionality so you can expect this in the next release.

**Comment by dynasticorpheus** [comment]
@SilleDE  Please let me know it works as expected. For each alarm mode a switch is created allowing you to set privacy mode. Note just like in the official app this is not possible for away mode.

**Comment by SilleDE** [comment]
It works as expected! Big thanks!
