### ISSUE TITLE
Problem after Update to 23.12.0

### ISSUE THREAD

**Issue by rolleff** [dynasticorpheus/gigasetelements-ha#29]
Hello,

i was very happy with the gigaset HAC in my Homeassist. Thanks a lot!
But since the update yesterday i can´t find my climate devices.

I have 1 Base station.
6 thermostats and 
1 Climate Sensor

Since the update, i only see 2 of the thermostats and the climate sensor.

All devices have the latest firmware. In the elements app, the devices are online.

Any ideas, what i can do?

Best regards,
Rolleff

**Comment by dynasticorpheus** [comment]
@rolleff  That is a shame, can you provide debug logs by adding below in you configuration.yaml and share the output?

```
logger:
  default: warn
  logs:
    custom_components.gigasetelements: debug
```

**Comment by rolleff** [comment]
@dynasticorpheus  Thank you for the quick support. 
I downgraded to the previous version, but without success.

Now i am on the latest version again and I found even without the debug code an error in the log. 

I hope it helps...

Thanks a lot.
regards Rolleff

`
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:359
Integration: Klima (documentation, issues)
First occurred: 06:07:57 (1 occurrences)
Last logged: 06:07:57

Error while setting up gigasetelements platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/gigasetelements/climate.py", line 41, in async_setup_platform
    GigasetelementsThermostat(
  File "/config/custom_components/gigasetelements/climate.py", line 62, in __init__
    self.update()
  File "/config/custom_components/gigasetelements/climate.py", line 134, in update
    self._target_temperature = round(float(self._sensor_attributes["setpoint"]), 1)
                                           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'setpoint'
`
[gigaset_debug.txt](https://github.com/dynasticorpheus/gigasetelements-ha/files/13555626/gigaset_debug.txt)

**Comment by dynasticorpheus** [comment]
@rolleff  Can you check if reverting  [db21a07](https://github.com/dynasticorpheus/gigasetelements-ha/commit/db21a07d9d617a37388e69de693c036eecf66b9d) resolves the issue?

e.g.  change `runtimeConfiguration` back into `states` on line 290 in the file `__init__.py`

Moreover can you add `_LOGGER.debug(self._elements_data)`  under line 45 so I can see how to fix this properly in case this does (not) work? This will dump the json response in the log file. Can you share this?

**Comment by rolleff** [comment]
@dynasticorpheus 

Great! Looks like it solved my problem. I can see the gigaset devices again!
Thanks a lot!

But have a problem with better thermostat now;-) 

Best regards
Rolleff

**Comment by dynasticorpheus** [comment]
@rolleff  Can you please still provide below so I can understand the actual problem and fix it for everyone? 

`Moreover can you add _LOGGER.debug(self._elements_data) under line 45 so I can see how to fix this properly in case this does (not) work? This will dump the json response in the log file. Can you share this?`

**Comment by rolleff** [comment]
> _LOGGER.debug(self._elements_data)

in file: binary_sensor ? 

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:359
Integration: Binärsensor (documentation, issues)
First occurred: 15:29:09 (1 occurrences)
Last logged: 15:29:09

Error while setting up gigasetelements platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/gigasetelements/binary_sensor.py", line 47, in async_setup_platform
    _LOGGER.debug(self._elements_data)
                  ^^^^
NameError: name 'self' is not defined

**Comment by dynasticorpheus** [comment]
@rolleff  I Just released **2023.12.1**  Can you please install using HACS and tell me if everything (still) works? 

I also introduced config option `enable_debug` which can be added to `configuration.yaml` and when set to `true` the json response is dumped to the log once. Can you do this and provide the output?  Once done you can set it to `false` or remove the line. 

```
gigasetelements:
  name: gigaset_elements
  username: abc
  password:  xyz
  enable_debug: true 

```

**Comment by rolleff** [comment]
@dynasticorpheus 

Can you tell me more detailed where i should paste the logging code?
under line 45 (Platforms,) it didnt work

**Comment by dynasticorpheus** [comment]
> @dynasticorpheus
> 
> Can you tell me more detailed where i should paste the logging code? under line 45 (Platforms,) it didnt work

See my previous comment, if you install latest version you can add debug option so no need to change code itself.

**Comment by rolleff** [comment]
@dynasticorpheus 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.gigasetelements
Source: custom_components/gigasetelements/__init__.py:164
Integration: Gigaset Elements (documentation, issues)
First occurred: 16:57:33 (1 occurrences)
Last logged: 16:57:33

API response object: {REMOVED}

**Comment by dynasticorpheus** [comment]
@rolleff  Below thermostat is showing error `"status": "errmove"` and  therefore has an empty `runtimeConfiguration`which was causing the error. Most recent version is able to handle this properly now. 

 I do think you need to physically check the device as my guess would be that `errmove` means the thermostat is unable to rotate and is somehow stuck?  Also `"connectionStatus": "offline"` does not look ok.

```
        {
          "id": "246A2C5D7EB3A3ED29F26275064B0237.02ebb2ce50",
          "type": "bs01.ts01",
          "friendlyName": "Hz Flur 2.OG",
          "firmwareStatus": "up_to_date",
          "firmwareVersion": "0062000010250000200403",
          "latestFirmwareVersion": "0062000010250000200403",
          "connectionStatus": "offline",
          "batteryStatus": "ok",
          "runtimeConfiguration": {},
          "states": {
            "temperature": 20.69,
            "status": "errmove",
            "setPoint": 21,
            "batterySaverMode": false
          },
          "frontendTags": {
            "room": {
              "roomName": "Flur 2.OG"
            }
          },
          "room": {
            "id": 748312,
            "friendlyName": "Flur 2.OG"
          },
          "capabilities": [],
          "debug": {
            "simple": "batteryLifetimePrediction: green",
            "extended": {
              "batteryLifetimePredictionColor": "green"
            }
          }
        }
```
