### ISSUE TITLE
 TEMP_CELSIUS is a deprecated constant

### ISSUE THREAD

**Issue by SilleDE** [dynasticorpheus/gigasetelements-ha#31]
I see this message in the log file:.

[homeassistant.const] TEMP_CELSIUS was used from gigasetelements, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead

Please adjust when you get the chance...

Best wishes
Sille

**Comment by dynasticorpheus** [comment]
Thanks for reporting  but already fixed under #30 and will be included in the next version.
