### ISSUE TITLE
Turn Siren on and off isolated

### ISSUE THREAD

**Issue by Macx82** [dynasticorpheus/gigasetelements-ha#4]
Hi!
Thank you für the great Plugin which works great in my HA Setup. I was thinking of expanding my Elements Security System with other components, f.e. hue motion sensors. For this purpose I tried to activate/deactivate the siren just isolated from happenings through the elements ecosystem. As far as I know (but I'm not an expert, but tried to get an answer via searching the weg) I can't trigger the siren cause its an binary sensor. Is that true und is there a possitility to switch the siren on and off without triggers from Elements?

Thank you very much in advance

**Comment by dynasticorpheus** [comment]
@Macx82  This should be possible as one can do this using the panic function in the app. Let me try and find the API call behind this.

**Comment by dynasticorpheus** [comment]
@Macx82  Implemented in latest version. An additional switch has been added which will trigger panic mode which on it's turn will trigger the siren. Please let me know if it works as expected. 5da4bb0

**Comment by Macx82** [comment]
@dynasticorpheus I tested it and it works perfect. Thank you very much for this enhancement and your efforts!
