### ISSUE TITLE
Alarm mode switches

### ISSUE THREAD

**Issue by Hveen28** [dynasticorpheus/gigasetelements-ha#5]
I am new in using Home Assistant. I installed your plugin via HACS. 
But I am confused about what the alarm mode switches do. 
If I set the switch 'home_mode' in HA then gigaset sets alarm mode ' Aangepast' and at movement the sirenes are yelling. In gigaset app I see icon 'Aangepast' is active. In gigaset configuration ' home_mode' means alarm dis-armed. Do I misunderstand the meaning of the switches? Please explane what is wrong.

**Comment by dynasticorpheus** [comment]
Hi @Hveen28  Alarm mode (names) are standardized in HASS hence I used below mapping, this ensures future development from either sides won't break things.  I have added this to the readme as this is a bit confusing when not made aware.

HASS <---> Gigaset

disarmed = home (alarm off)
arm_home = custom
arm_away = away
arm_night = night

So switch off means gigaset home mode
