### ISSUE TITLE
Updating gigasetelements sensor took longer

### ISSUE THREAD

**Issue by Hveen28** [dynasticorpheus/gigasetelements-ha#6]
I get warning: WARNING (MainThread) [homeassistant.components.sensor] Updating gigasetelements sensor took longer than the scheduled update interval 0:00:10, and is repeating without end. It only stops after reboot HASS. It happens if I set alarm mode to 'Home' with gigaset app (from mode 'Night'). In HASS the switch 'night-mode' was on. After reboot no switch is on, while I expect switch 'Home-mode' would be on, because in gigaset app ' Home' icon is active. By the way, in HASS no gigaset switches are on at all, only if I set alarm mode to 'night' with gigaset app, in HASS switch 'night-mode' is on.

**Comment by dynasticorpheus** [comment]
Hi @Hveen28  Please note the reply I gave on mode mappings in the other issue you raised. Also note that the alarm modes get synced after 30 seconds in case it is set outside home assistant. (e.g. is changed using the gigaset elements app)

_"Updating gigasetelements sensor took longer than the scheduled update interval 0:00:10"_ I do not have this issue so without any logs it's hard to say anything.

**Comment by Hveen28** [comment]
Hi @dynasticorpheus, thanks for your answer. The meaning of the mode switches is clear now. About the update interval I will see what happens next days. If the problem stays, I will ask you what logs you to look at the problem.

**Comment by dynasticorpheus** [comment]
@Hveen28  Sure feel free to re-open the issue. I will release a new version soon which will do less API calls when refreshing perhaps this helps.
